name: "Publish"

permissions:
  actions: read
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  version-and-push:
    name: "Version and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: secrets.PAT
          username: "tyler-suderman-kr"
          ssh-string: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - name: Configure git
        run: |
          git config --global --replace-all user.name "$GITHUB_ACTOR"
          git config --global --replace-all user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Version root package
        run: npm run version:root patch

      - name: Bump NPM version and push
        id: bumpAndPush
        run: npm run publish:all patch
