name: "Publish"

permissions:
  actions: read
  contents: write
  id-token: write

on:
  workflow_dispatch: 

jobs:
  version-and-push:
    name: "Version and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

        #   token: ${{ secrets.PAT }}
        #   always-auth: true
        #   registry-url: https://npm.pkg.github.com
        #   scope: "@tyler-suderman-kr"

      # - name: Authenticate with private NPM package
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT }}" > ~/.npmrc
      #     echo `cat ~/.npmrc`

      # - name: Check stuff
      #   run: |
      #     npm --version
      #     node --version

      - run: npm install

      - run: npm run build

      - name: Configure git
        run: |
          git config --global --replace-all user.name "$GITHUB_ACTOR"
          git config --global --replace-all user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Version root package
        run: npm run version:root patch

      - name: Bump NPM version and push
        # env:
        #   GH_TOKEN: ${{ secrets.PAT }}
        id: bumpAndPush
        run: npm run publish:all patch
